name: Compile ESP32

on:
  push:
    paths:
      - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32wrover
          sketch-path: ./
          output-path: ./compiled

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: esp32-firmware
          path: ./compiled
